name: Fetch Planning Applications

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-applications:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright beautifulsoup4
        playwright install chromium
    
    - name: Run fetch script
      run: python fetch_sibford_planning_applications.py
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add applications.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update planning applications" && git push) 